
[crunch]
api_key = "yapk-MOF1u6SqSyb8wHNeBYvbPlPQHaE7xbMZeYgkpVLqebY="
api_url = "https://crunch.io/api/"
username = "ian.ritchie@yougov.com"
password = "L0RDH0rus112358"

[other_services]
# Add other API credentials as needed