# config.yml

app:
  name: "Survey Weighting Suite"
  version: "2.14.0"
  debug: false
  
settings:
  max_upload_size: 314572800  # 300MB
  max_rows: 1000000
  max_iterations: 100
  default_convergence_threshold: 0.001
  default_theme: 'blueberry'  # Updated default theme

# update to YouGov colorz lulz  
theme:
  current: "blueberry"  # default theme
  presets:
    grapefruit:
      core: "#FF412C"
      light_60: "#FF8080"
      light_80: "#FF6756"
      dark_1: "#E8281F"
      dark_2: "#C20400"
    plum:
      core: "#9F29FF"
      light_60: "#C57FFF"
      light_80: "#B254FF"
      dark_1: "#801DB8"
      dark_2: "#660AB8"
    blueberry:
      core: "#0684EE"
      light_60: "#B9CAF5"
      light_80: "#88B8F1"
      dark_1: "#0051B9"
      dark_2: "#003CA8"
    avocado:
      core: "#41CA4B"
      light_60: "#83DFCB"
      light_80: "#5AC8A8"
      dark_1: "#1B8B78"
      dark_2: "#008B45"
    pomegranate:
      core: "#FF2A80"
      light_60: "#FF7BB3"
      light_80: "#FF4B90"
      dark_1: "#CB0429"
      dark_2: "#A50165"
  
methods:
  post_stratification:
    enabled: true
    max_strata: 100
    
  raking:
    enabled: true
    max_dimensions: 10
    
  calibration:
    enabled: true
    default_bounds: [0, 10]
    
  ipw:
    enabled: true
    supported_models:
      - logistic
      - random_forest
      - gbm

export:
  formats:
    - csv
    - xlsx
    - sav
    - rds
  max_size: 524288000  # 500MB
  
logging:
  level: "INFO"
  file: "logs/app.log"
  max_size: 104857600  # 100MB
  backup_count: 5
  
security:
  max_file_size: 314572800  # 300MB
  allowed_extensions:
    - .csv
    - .xlsx
    - .sav
    - .rds

shiny:
  maxRequestSize: 314572800  # 300MB
  maxFileSize: 314572800  # 300MB

